[[redirects]]
  from = "/"
  to = "https://github.com/vmware-tanzu/pinniped"
  status = 302
  force = true

[[redirects]]
  from = "/meet"
  to = "https://VMware.zoom.us/j/94638309756?pwd=V3NvRXJIdDg5QVc0TUdFM2dYRzgrUT09"
  status = 302
  force = true
